---
driver:
  name: ec2
  instance_type: t2.micro

transport:
  username: ubuntu

provisioner:
  name: shell

platforms:
  - name: aws/nginx64
    driver: 
      image_id: ami-0dc18788ad86d0562
      region: us-east-2

verifier:
  name: inspec
  sudo: false

suites:
  - name: default

  
